export const SELECT_IMAGE = 'SELECT_IMAGE'
export const UNSELECT_IMAGE = 'UNSELECT_IMAGE'

export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'
export const DELETE_SEARCH = 'DELETE_SEARCH'
